import { Inter, Merriweather } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Background from "@/components/Background";

export const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["700", "900"], // for strong headlines
  display: "swap",
  variable: "--font-merriweather",
});

export const metadata = {
  title: "Veritium",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${merriweather.variable} antialiased`}
      >
        <Background />
        <Navbar />

        {children}
      </body>
    </html>
  );
}
