// import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Merriweather } from "next/font/google";
import "../../app/globals.css";

export const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["700", "900"], // for strong headlines
  display: "swap",
  variable: "--font-merriweather",
});

export const metadata = {
  title: "Veritium",
  // description: "Generated by create next app",
};

export default function HowItWorksLayout({ children }) {
  return (
    <div>
      {children} {/* No Navbar or Background */}
    </div>
  );
}
