"""create claim_events table

Revision ID: 1b913933dc46
Revises: 6b1cc52eca77
Create Date: 2025-08-24 16:56:32.974897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1b913933dc46'
down_revision: Union[str, Sequence[str], None] = '6b1cc52eca77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_events',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('claim_id', sa.INTEGER(), nullable=True),
        sa.Column('actor_id', sa.INTEGER(), nullable=True),
        sa.Column('source_id', sa.INTEGER(), nullable=True),
        sa.Column('event_type', sa.TEXT(), nullable=False),
        sa.Column('url', sa.TEXT(), nullable=True),
        sa.Column('content_excerpt', sa.TEXT(), nullable=True),
        sa.Column('language', sa.TEXT(), nullable=True),
        sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('collected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('reshares', sa.INTEGER(), server_default='0', nullable=False),
        sa.Column('replies', sa.INTEGER(), server_default='0', nullable=False),
        sa.Column('reactions', sa.INTEGER(), server_default='0', nullable=False),
        sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint("event_type IN ('said','shared','debunked','referenced')")
    )
    
    # Indexes
    op.create_index('uq_claim_events_url', 'claim_events', [sa.text('lower(url)')], unique=True, postgresql_where=sa.text('url IS NOT NULL'))
    op.create_index('idx_claim_events_claim_time', 'claim_events', ['claim_id', 'published_at'], unique=False)
    op.create_index('idx_claim_events_actor_time', 'claim_events', ['actor_id', 'published_at'], unique=False)
    op.create_index('idx_claim_events_source_time', 'claim_events', ['source_id', 'published_at'], unique=False)
    op.create_index('idx_claim_events_type_time', 'claim_events', ['event_type', 'published_at'], unique=False)
    op.create_index('gin_claim_events_excerpt', 'claim_events', ['content_excerpt'], unique=False, postgresql_using='gin', postgresql_ops={'content_excerpt': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('gin_claim_events_excerpt', table_name='claim_events')
    op.drop_index('idx_claim_events_type_time', table_name='claim_events')
    op.drop_index('idx_claim_events_source_time', table_name='claim_events')
    op.drop_index('idx_claim_events_actor_time', table_name='claim_events')
    op.drop_index('idx_claim_events_claim_time', table_name='claim_events')
    op.drop_index('uq_claim_events_url', table_name='claim_events')
    op.drop_table('claim_events')
    # ### end Alembic commands ###
