"""Alter claims table and add trigger

Revision ID: 1dce076c49b8
Revises: 3310470c6937
Create Date: 2025-08-24 16:53:48.180377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dce076c49b8'
down_revision: Union[str, Sequence[str], None] = '3310470c6937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('source_id', sa.INTEGER(), nullable=True))
    op.add_column('claims', sa.Column('fact_checker_id', sa.INTEGER(), nullable=True))
    op.add_column('claims', sa.Column('language', sa.TEXT(), nullable=True))
    op.add_column('claims', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    
    op.create_foreign_key('fk_claims_source_id', 'claims', 'sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_claims_fact_checker_id', 'claims', 'actors', ['fact_checker_id'], ['id'], ondelete='SET NULL')

    # Trigger function and trigger creation
    op.execute("""
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at := NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER claims_set_updated_at
        BEFORE UPDATE ON claims
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    """)

    # Create indexes
    op.create_index(op.f('idx_claims_published_date'), 'claims', ['published_date'], unique=False)
    op.create_index(op.f('idx_claims_source_id'), 'claims', ['source_id'], unique=False)
    op.create_index(op.f('idx_claims_fact_checker_id'), 'claims', ['fact_checker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_claims_fact_checker_id'), table_name='claims')
    op.drop_index(op.f('idx_claims_source_id'), table_name='claims')
    op.drop_index(op.f('idx_claims_published_date'), table_name='claims')

    # Drop trigger and function
    op.execute('DROP TRIGGER IF EXISTS claims_set_updated_at ON claims;')
    op.execute('DROP FUNCTION IF EXISTS set_updated_at();')

    op.drop_constraint('fk_claims_fact_checker_id', 'claims', type_='foreignkey')
    op.drop_constraint('fk_claims_source_id', 'claims', type_='foreignkey')

    op.drop_column('claims', 'updated_at')
    op.drop_column('claims', 'language')
    op.drop_column('claims', 'fact_checker_id')
    op.drop_column('claims', 'source_id')
    # ### end Alembic commands ###