"""create helper views

Revision ID: 24bad87021b8
Revises: 57ebdfa9e91d
Create Date: 2025-08-24 17:00:02.673426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '24bad87021b8'
down_revision: Union[str, Sequence[str], None] = '57ebdfa9e91d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE OR REPLACE VIEW v_claim_activity AS
    SELECT
      c.id AS claim_id,
      c.claim_text,
      c.verdict,
      c.published_date,
      COUNT(e.id) AS total_events,
      MAX(e.published_at) AS last_seen_at
    FROM claims c
    LEFT JOIN claim_events e ON e.claim_id = c.id
    GROUP BY c.id;
    """)
    
    op.execute("""
    CREATE OR REPLACE VIEW v_top_amplifiers_7d AS
    SELECT
      a.id AS actor_id,
      a.platform,
      a.handle,
      COUNT(e.id) AS posts_7d
    FROM actors a
    JOIN claim_events e ON e.actor_id = a.id
    WHERE e.published_at >= NOW() - INTERVAL '7 days'
    GROUP BY a.id, a.platform, a.handle
    ORDER BY posts_7d DESC;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS v_top_amplifiers_7d;")
    op.execute("DROP VIEW IF EXISTS v_claim_activity;")
    # ### end Alembic commands ###
