"""Add claims.raw_analysis_json

Revision ID: 2e58dd67e9b4
Revises: 70090d7735f2
Create Date: 2025-08-27 18:51:42.360403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e58dd67e9b4'
down_revision: Union[str, Sequence[str], None] = '70090d7735f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('raw_analysis_json', sa.Text(), nullable=True))
    op.alter_column('claims', 'simhash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'simhash',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('claims', 'raw_analysis_json')
    # ### end Alembic commands ###
