"""Create sources and actors tables

Revision ID: 3310470c6937
Revises: 
Create Date: 2025-08-24 16:41:21.943095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3310470c6937'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Optional but useful extensions
    # Use op.execute to run raw SQL for commands not directly supported by Alembic API
    op.execute('CREATE EXTENSION IF NOT EXISTS citext;')
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')

    # Create sources table
    op.create_table('sources',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('domain', postgresql.CITEXT(), nullable=False),
        sa.Column('kind', sa.TEXT(), nullable=False),
        sa.Column('name', sa.TEXT(), nullable=True),
        sa.Column('country_code', sa.CHAR(length=2), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('domain', 'kind'),
        sa.CheckConstraint("kind IN ('fact_checker','news','social','gov','ngo','blog','forum','other')")
    )
    op.create_index(op.f('idx_sources_domain'), 'sources', ['domain'], unique=False)

    # Create actors table
    op.create_table('actors',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('platform', sa.TEXT(), nullable=False),
        sa.Column('handle', postgresql.CITEXT(), nullable=True),
        sa.Column('display_name', sa.TEXT(), nullable=True),
        sa.Column('source_id', sa.INTEGER(), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('platform', 'handle'),
        sa.CheckConstraint("platform IN ('x','reddit','telegram','youtube','facebook','instagram','news','website','fact_checker','other')")
    )
    op.create_index(op.f('idx_actors_source_id'), 'actors', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_actors_source_id'), table_name='actors')
    op.drop_table('actors')
    
    op.drop_index(op.f('idx_sources_domain'), table_name='sources')
    op.drop_table('sources')
    
    # Extensions are not typically dropped in a downgrade
    # unless you are sure they are not used by anything else.
    # op.execute('DROP EXTENSION IF EXISTS pg_trgm;')
    # op.execute('DROP EXTENSION IF EXISTS citext;')
    # ### end Alembic commands ###
