"""create variant clustering tables

Revision ID: 57ebdfa9e91d
Revises: fc12203f20a5
Create Date: 2025-08-24 16:58:27.951318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57ebdfa9e91d'
down_revision: Union[str, Sequence[str], None] = 'fc12203f20a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variant_clusters',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('label', sa.TEXT(), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('event_variants',
        sa.Column('event_id', sa.BIGINT(), nullable=False),
        sa.Column('variant_id', sa.BIGINT(), nullable=False),
        sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['claim_events.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['variant_id'], ['variant_clusters.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('event_id', 'variant_id')
    )
    op.create_index(op.f('idx_event_variants_variant'), 'event_variants', ['variant_id'], unique=False)

    op.create_table('claim_variants',
        sa.Column('claim_id', sa.INTEGER(), nullable=False),
        sa.Column('variant_id', sa.BIGINT(), nullable=False),
        sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['variant_id'], ['variant_clusters.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('claim_id', 'variant_id')
    )
    op.create_index(op.f('idx_claim_variants_variant'), 'claim_variants', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_claim_variants_variant'), table_name='claim_variants')
    op.drop_table('claim_variants')
    op.drop_index(op.f('idx_event_variants_variant'), table_name='event_variants')
    op.drop_table('event_variants')
    op.drop_table('variant_clusters')
    # ### end Alembic commands ###
