"""Create entities and claim_entities tables

Revision ID: 6b1cc52eca77
Revises: 1dce076c49b8
Create Date: 2025-08-24 16:55:17.161835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6b1cc52eca77'
down_revision: Union[str, Sequence[str], None] = '1dce076c49b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
        sa.Column('id', sa.INTEGER(), primary_key=True),
        sa.Column('name', postgresql.CITEXT(), nullable=False),
        sa.Column('kind', sa.TEXT(), nullable=True),
        sa.Column('lang', sa.TEXT(), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint("name", "kind", "lang", name="uq_entities_name_kind_lang"),
        sa.CheckConstraint("kind IN ('person','org','place','topic','other')", name="chk_entities_kind")
    )
    
    op.create_table('claim_entities',
        sa.Column('claim_id', sa.INTEGER(), nullable=False),
        sa.Column('entity_id', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('claim_id', 'entity_id')
    )
    op.create_index(op.f('idx_claim_entities_claim'), 'claim_entities', ['claim_id'], unique=False)
    op.create_index(op.f('idx_claim_entities_entity'), 'claim_entities', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_claim_entities_entity'), table_name='claim_entities')
    op.drop_index(op.f('idx_claim_entities_claim'), table_name='claim_entities')
    op.drop_table('claim_entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
