"""Change claims.simhash column type to String

Revision ID: 70090d7735f2
Revises: b4a08b900544
Create Date: 2025-08-26 16:33:20.690563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '70090d7735f2'
down_revision: Union[str, Sequence[str], None] = 'b4a08b900544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('gin_claim_events_excerpt'), table_name='claim_events', postgresql_ops={'content_excerpt': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('uq_claim_events_url'), table_name='claim_events', postgresql_where='(url IS NOT NULL)')
    op.alter_column('claims', 'simhash',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_claims_fact_checker_id'), table_name='claims')
    op.drop_index(op.f('idx_claims_published_date'), table_name='claims')
    op.drop_index(op.f('idx_claims_source_id'), table_name='claims')
    op.drop_constraint(op.f('uq_entities_name_kind_lang'), 'entities', type_='unique')
    op.create_unique_constraint('uq_entity_name_kind_lang', 'entities', ['name', 'kind', 'lang'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_entity_name_kind_lang', 'entities', type_='unique')
    op.create_unique_constraint(op.f('uq_entities_name_kind_lang'), 'entities', ['name', 'kind', 'lang'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_claims_source_id'), 'claims', ['source_id'], unique=False)
    op.create_index(op.f('idx_claims_published_date'), 'claims', ['published_date'], unique=False)
    op.create_index(op.f('idx_claims_fact_checker_id'), 'claims', ['fact_checker_id'], unique=False)
    op.alter_column('claims', 'simhash',
               existing_type=sa.String(length=20),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.create_index(op.f('uq_claim_events_url'), 'claim_events', [sa.literal_column('lower(url)')], unique=True, postgresql_where='(url IS NOT NULL)')
    op.create_index(op.f('gin_claim_events_excerpt'), 'claim_events', ['content_excerpt'], unique=False, postgresql_ops={'content_excerpt': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
