"""create daily metrics tables

Revision ID: fc12203f20a5
Revises: 1b913933dc46
Create Date: 2025-08-24 16:57:34.136557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fc12203f20a5'
down_revision: Union[str, Sequence[str], None] = '1b913933dc46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_metrics_daily',
        sa.Column('actor_id', sa.INTEGER(), nullable=False),
        sa.Column('date', sa.DATE(), nullable=False),
        sa.Column('posts', sa.INTEGER(), server_default='0', nullable=False),
        sa.Column('unique_claims', sa.INTEGER(), server_default='0', nullable=False),
        sa.Column('origin_score', sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column('amplifier_score', sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column('coordinated_score', sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column('false_share_count', sa.INTEGER(), server_default='0', nullable=False),
        sa.Column('trust_score', sa.DOUBLE_PRECISION(), nullable=True),
        sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('actor_id', 'date')
    )
    op.create_index(op.f('idx_actor_metrics_trust'), 'actor_metrics_daily', ['date', 'trust_score'], unique=False)

    op.create_table('source_metrics_daily',
        sa.Column('source_id', sa.INTEGER(), nullable=False),
        sa.Column('date', sa.DATE(), nullable=False),
        sa.Column('posts', sa.INTEGER(), server_default='0', nullable=False),
        sa.Column('unique_actors', sa.INTEGER(), server_default='0', nullable=False),
        sa.Column('false_rate', sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column('accuracy_rate', sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column('avg_burstiness', sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column('trust_score', sa.DOUBLE_PRECISION(), nullable=True),
        sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('source_id', 'date')
    )
    op.create_index(op.f('idx_source_metrics_trust'), 'source_metrics_daily', ['date', 'trust_score'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_source_metrics_trust'), table_name='source_metrics_daily')
    op.drop_table('source_metrics_daily')
    op.drop_index(op.f('idx_actor_metrics_trust'), table_name='actor_metrics_daily')
    op.drop_table('actor_metrics_daily')
    # ### end Alembic commands ###
